name: CI
on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        env: 
          token: ${{ secrets.TOKENS }}
          chatid: ${{ secrets.chatid }}
        run: | 
         curl https://api.telegram.org/bot$token/sendMessage\?text\=hello\&chat_id\=$chatid > /dev/null
         curl ready
