name: CI
on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        env: 
          host: ${{ secrets.TOKEN }}
        run: echo "$host"
